image:
  name: loadimpact/k6
  entrypoint: [""]

stages:
  - build
  - validate
  - test

build:
  stage: build
  image: node:16-alpine3.16
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/

validate:
  stage: validate
  dependencies:
    - build
  script:
    - k6 run dist/test-orchestrator.js -e ITERATION_OVERRIDE=1

execute:
  only:
    - manual
  stage: test
  dependencies:
    - build
  script:
    - k6 run -o cloud dist/test-orchestrator.js -e K6_PROJECT_ID=$K6_CLOUD_ID

