image:
  name: registry.gitlab.com/answerdigital/qe-capability/templates/typescriptk6projecttemplate:no-pw
  entrypoint: [""]

stages:
  - build
  - validate
  - test

build:
  stage: build
  image: node:16-alpine3.16
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

validate:
  stage: validate
  dependencies:
    - build
  script:
    - npm run validate

execute:
  only:
    - manual
  stage: test
  dependencies:
    - build
  script:
    - npm run test -- -e K6_PROJECT_ID=$K6_CLOUD_ID

