image:
  name: loadimpact/k6
  entrypoint: [""]

stages:
  - validate
  - test

validate:
  stage: validate
  script:
    - k6 run src/test-orchestrator.js -e ITERATION_OVERRIDE=1

execute:
  only:
    - manual
  stage: test
  script:
    - k6 run -o cloud src/test-orchestrator.js -e K6_PROJECT_ID=$K6_CLOUD_ID

