FROM mcr.microsoft.com/playwright:v1.29.0-focal

RUN apt-get update && apt-get install -y \
  build-essential \
  wget \
  git

ENV GO_DOWNLOAD_URL=https://go.dev/dl/go1.19.4.linux-amd64.tar.gz
RUN wget -q $GO_DOWNLOAD_URL -O go.tar.gz \
  && tar -C /usr/local -xzf go.tar.gz \
  && rm go.tar.gz

ENV PATH=$PATH:/usr/local/go/bin
ENV PATH=$PATH:/go/bin

ENV GOPATH=/go

RUN go install go.k6.io/xk6/cmd/xk6@latest

WORKDIR /go/bin
RUN ./xk6 build --output xk6-playwright --with github.com/wosp-io/xk6-playwright
RUN go run github.com/playwright-community/playwright-go/cmd/playwright@latest install --with-deps