on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:
    
jobs:
  validate-test:
    name: k6-run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
      - name: Install Cross-OS tool
        run: npm i -g cross-os
      - name: Install Prism
        run: npm install -g @stoplight/prism-cli
      - name: Install k6
        run: |
          curl https://github.com/grafana/k6/releases/download/v0.43.1/k6-v0.43.1-linux-amd64.tar.gz -L | tar xvz --strip-components 1
      - name: Install packages
        run: |
          npm install
      - name: Start server and run tests
        run: |
          prism mock https://raw.githubusercontent.com/AnswerConsulting/AnswerKingAPI/main/AnswerKingAPI.yml &
          sleep 5          
          K6_PROMETHEUS_RW_SERVER_URL=https://prometheus-prod-05-gb-south-0.grafana.net/api/prom/push
          ./k6 run ./src/test-orchestrator.js -e ITERATION_OVERRIDE=1 -o experimental-prometheus-rw
          
