on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:
    
jobs:
  validate-test:
    name: k6-run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
      - name: Install Cross-OS tool
        run: npm i -g cross-os
      - name: Install Prism
        run: npm install -g @stoplight/prism-cli
      - name: Install k6
        run: |
          curl https://github.com/loadimpact/k6/releases/download/v0.26.2/k6-v0.26.2-linux64.tar.gz -L | tar xvz --strip-components 1
      - name: Install packages
        run: |
          npm install
      - name: Start server and run tests
        run: |
          npm run start-mock-server
          k6 run ./src/test-orchestrator.js -e ITERATION_OVERRIDE=1
        
        
